FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=saegh123
ENV N8N_BASIC_AUTH_PASSWORD=Sepehr@2025!
ENV N8N_HOST=fly-n8n
ENV WEBHOOK_URL=https://fly-n8n.fly.dev/
ENV N8N_PORT=5678
ENV DB_SQLITE_VACUUM_ON_STARTUP=true

EXPOSE 5678
CMD ["n8n", "start"]
